spring:
  application:
    name: product-stock-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productstockdb?autoReconnect=true
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
      
server:
  port: ${port:8200}
