spring:
  application:
    name: product-enquiry-service

server:
  port: ${port:8300}
  
#eureka:
#  client:
#    enabled: false  

#product-stock-service:
# ribbon:
#  listOfServers: http://localhost:8300, http://localhost:8301